config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about_us'

  get 'contact' => 'static_pages#contact'
  
  resources :products , only: [:show, :index], path: 'products'
  resources :portofolios , only: [:show, :index], path: 'portofolios'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portofolio.rb
class Portofolio < ApplicationRecord
  has_many :portofolio_images
  validates :portofolio_images, :presence => {:message => "=> You have to upload at least one image for each category!"}
  accepts_nested_attributes_for :portofolio_images, allow_destroy: true
  paginates_per 3
end

app/models/portofolio_image.rb
class PortofolioImage < ApplicationRecord
  belongs_to :portofolio
  validates :category, :presence => {:message => '=> You must choose category!'}
  mount_uploader :name, ImageUploader
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images
  validates :product_images, :presence => {:message => "=> You have to upload at least one image for each category!"}
  accepts_nested_attributes_for :product_images, allow_destroy: true
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  validates :category, :presence => {:message => '=> You must choose category!'}
  mount_uploader :name, ImageUploader
end

app/models/slider_image.rb
class SliderImage < ApplicationRecord
  mount_uploader :name, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/portofolios_controller.rb
class PortofoliosController < ApplicationController
  def show
    @portofolio = Portofolio.find(params[:id])
    @portofolio_images = @portofolio.portofolio_images.where(category: "gallery")
    @portofolio_thumbnail = @portofolio.portofolio_images.where(category: "thumbnail")
  end

  def index
    @portofolios = Portofolio.all
    @portofolios = Kaminari.paginate_array(@portofolios).page(params[:page]).per(3)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    @product_images = @product.product_images.where(category: "gallery")
    @product_thumbnail = @product.product_images.where(category: "thumbnail")
  end

  def index
    @products = Product.all
  end



end

app/controllers/slider_images_controller.rb
class SliderImagesController < ApplicationController
  def show
    @slider_image = SliderImage.find(params[:id])
  end
  def index
    @slider_images = SliderImage.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @slider_images = SliderImage.all
    @products = Product.all
    @portofolios = Portofolio.all
  end

  def about_us
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portofolios_helper.rb
module PortofoliosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/slider_images_helper.rb
module SliderImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_footer.html.erb
<footer id="fh5co-footer" role="contentinfo">
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          &copy; 2017 PT. Surya Cipta Adhi Estetika
        <p>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/application/_gototop.html.erb
<div class="gototop js-top">
  <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>

app/views/application/_navigation.html.erb
<nav class="fh5co-nav" role="navigation">
    <div class="cont">
      <div class="row">
        <div class="logo text-center">
          <div id="fh5co-logo">
            <%= link_to image_tag('Logo.png', :class => "logo-scae"), root_path %>
          </div>
          <h4>PT. Surya Cipta Adhi Estetika</h4>
        </div>
        <div class="left-menu menu-1 menu-nav">
          <ul>
            <li><%= link_to "ABOUT", about_path %></li>
            <li><%= link_to "PRODUCTS", products_path %></li>
            <li><%= link_to "PORTOFOLIOS", portofolios_path %></li>
            <li><%= link_to "CONTACT", contact_path %></li>
          </ul>
        </div>
        <!-- <div class="right-menu text-left menu-1 menu-nav">
          <ul>
            <li class="btn-cta"><a href="#"><span>Login</span></a></li>
          </ul>
        </div> -->
      </div>
      
    </div>
  </nav>

app/views/application/_slider.html.erb
<div id="carousel-example-generic" class="carousel slide fh5co-cover" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @slider_images.each_with_index do |outing, i| %>
      <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%'active' if i == 0 %>"></li>
    <% end %>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <%- @slider_images.each_with_index do |s, index| %>
      <div class="item fh5co-cover <% if index == 0 %> active <% end %> ">
          <%= image_tag (s.name.url(:slider)) %>
      </div>
    <% end %>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
<!-- Carousel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Surya Cipta Adhi Estetika</title>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta name="description" content="Web Design and Development" />
  	<meta name="author" content="rakarsa" />
  	<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
    <div class="fh5co-loader"></div>
    <div id="page">
      <%= render 'navigation' %>
      <%= yield %>
      <%= render 'footer' %>
    </div>
    <%= render 'gototop' %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBzP1Bc3ZsIDhb7a2nnWsnpLdx2OrY6z3w&callback=initMap"></script>
  </body>
</html>

app/views/portofolios/index.html.erb
<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url(<%= asset_path 'img_bg_4.jpg' %>);">
  <!-- <div class="overlay"></div> -->
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <div class="display-t">
          <div class="display-tc animate-box" data-animate-effect="fadeIn">
            <h1>Portofolios</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
      
<div id="fh5co-project">
  <div class="container">
    <div class="row">
      <% @portofolios.each do |p| %>
          <div class="col-md-12 col-sm-12 fh5co-project animate-box" data-animate-effect="fadeIn">
            <%= link_to (p) do %>
              <%= image_tag(p.portofolio_images.find_by(category:'thumbnail').name.url(:porto_thumb)) %> 
              <h3><%= p.title %></h3>
            <% end %> 
          </div>  
      <% end %>
    </div>
  </div>
      
  <div class="container">
    <div class="row">
      <div class="text-center">         
        <nav aria-label="Page navigation">
          <!-- <ul class="pagination ">
            <li>
              <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
              <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul> -->
        <%= paginate @portofolios, :theme => 'twitter-bootstrap-3' %>

        </nav>
      </div>
    </div>
  </div>
</div>

app/views/portofolios/show.html.erb
<div class="product-container">
    <div class="container">
      <div class="about-content">
        <div class="row animate-box">
          <div class="col-md-12 ">
            <%- @portofolio_images.each_with_index do |img1, i| %>
              <% if i == 0 %>
                <%= image_tag (img1.name.url(:porto_show)), :class => "img-responsive" %>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-4 ">
            <div class="product-name">
              <h3><%= @portofolio.client %></h3>
              <h3><%= @portofolio.year %></h3>
            </div>
          </div>
            <div class="col-md-8"> 
              <p><%= @portofolio.portofolio_desc %></p>
            </div>
            <div class="col-md-12 text-center">
              <%- @portofolio_images.each do |img| %>
              <%= image_tag (img.name.url), :class => "img-responsive" %>
              <% end %>
              <div class="col-md-2 col-md-offset-5 col-sm-6">
                <%= link_to portofolios_path do %>
                  <button type="" class="btn-scae-stroke-white">All Portofolios</button>
                <% end %>
              </div>
            </div>
          
        </div>
      </div>
    </div>
  </div>

app/views/products/index.html.erb
<header id="fh5co-header" class="fh5co-cover products-cover" role="banner" style="background-image:url(<%= asset_path 'FullSizeRender.jpg' %>); ">
  <!-- <div class="overlay"></div> -->
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <div class="display-t">
          <div class="display-tc animate-box" data-animate-effect="fadeIn">
            <h1>Products</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<div id="fh5co-project">
  <div class="container">
    <div class="row">
      <% @products.each do |p| %>
          <div class="col-md-4 col-sm-6 fh5co-project animate-box" data-animate-effect="fadeIn">
            <%= link_to (p) do %>
              <%= image_tag(p.product_images.find_by(category:'thumbnail').name.url(:thumbnail)) %>
              <h3><%= p.name %></h3>
            <% end %> 
          </div>  
      <% end %>

    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="product-container">
    <div class="container">
      <div class="about-content">
        <div class="row animate-box">
          <div class="col-md-12 ">
            <%- @product_images.each_with_index do |img1, i| %>
              <% if i == 0 %>
                <%= image_tag (img1.name.url(:porto_show)), :class => "img-responsive" %>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-4 ">
            <div class="product-name">
              <h3><%= @product.name %></h3>
            </div>
          </div>
            <div class="col-md-8"> 
              <p><%= @product.product_desc %></p>
            </div>
            <div class="col-md-12 text-center">
              <%- @product_images.each do |img| %>
              <%= image_tag (img.name.url), :class => "img-responsive" %>
              <% end %>
              <div class="col-md-2 col-md-offset-5 col-sm-6">
                <%= link_to products_path do %>
                  <button type="" class="btn-scae-stroke-white">All Products</button>
                <% end %>
              </div>
            </div>
          
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/about_us.html.erb
<header id="fh5co-header" class="fh5co-cover about-cover" role="banner" style="background-image: url(<%= asset_path 'img_bg_3.jpg' %>);" >
	<!-- <div class="overlay"></div> -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center">
				<div class="display-t">
					<div class="display-tc animate-box" data-animate-effect="fadeIn">
						<h1>About Us</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

<div id="fh5co-about">
	<div class="container">
		<div class="about-content">
			<div class="row animate-box">
                  <div class="col-md-6 ">
					<%= image_tag ('img_bg_1.jpg'), :class => "img-responsive", :alt => "about" %>
				</div>
				<div class="col-md-6 ">
					<div class="desc">
						<h3>Vision</h3>
						<p>To be the most successful and respected carpets distributor company that leads in Indonesia and Southeast Asia. With commitment, we build intregrity and trust for our customers</p> 
					</div>
					<div class="desc">
						<h3>Mission</h3>
						<p>Strengthen the collaboration with costumers by good communication and cooperation and providing our best products and services. In order to fulfill the highest customer satisfaction. </p> 
					</div>
				</div>
				
			</div>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<header id="fh5co-header" class="fh5co-cover contact-cover" role="banner" style="background-image: url(<%= asset_path 'img_bg_7.jpg' %>);">
	<!-- <div class="overlay"></div> -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center">
				<div class="display-t">
					<div class="display-tc animate-box" data-animate-effect="fadeIn">
						<h1>Contact Us</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

<div id="fh5co-contact">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-push-1 animate-box">
				
				<div class="fh5co-contact-info">
					<h3>Contact Information</h3>
					<ul>
						<li class="address">Jl. Grinting II No. 19, Blok A <br> Kebayoran Baru, Jakarta Selatan</li>
						<li class="phone"><a href="tel://1234567920">+6221-7220057</a></li>
						<li class="email"><a href="mailto:scaecarpet@gmail.com">scaecarpet@gmail.com</a></li>

					</ul>
				</div>

			</div>
			<div class="col-md-6 animate-box">
				<h3>Get In Touch</h3>
					<div id="map" class="fh5co-map"></div>
			</div>
		</div>
		
	</div>
</div>

app/views/static_pages/home.html.erb
<header id="fh5co-header" class="fh5co-cover" role="banner" >
	<%= render 'slider' %>
  <!-- <div class="overlay"></div> -->
  <div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center">
            <div class="display-t">
                <div class="display-tc animate-box" data-animate-effect="rotateIn">
                    <!-- <h1>PT. Surya Cipta Adhi Estetika</h1> -->
                    <!-- <h2>The leading customized carpets</h2> -->
                </div>
            </div>
        </div>
    </div>
  </div>
</header>

<div id="fh5co-services" class="fh5co-bg-section">
	<div class="container">
		<div class="row">
              <div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Why Us?</h2>
				<div class="strip"></div>
			</div>
		</div>
			<div class="col-md-3 col-sm-3">
				<div class="feature-center animate-box text-center" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-eye"></i>
					</span>
					<h3>Customizable</h3>
					<p>With experienced, skilled designer, and professional techniques on producing carpets to be a perfect accent for any living space as our customers needs. </p>
				</div>
			</div>
			<div class="col-md-3 col-sm-3">
				<div class="feature-center animate-box text-center" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-box"></i>
					</span>
					<h3>Good Installation</h3>
					<p>We provide good Installation with high-skilled and experienced installation team.</p>
				</div>
			</div>
			<div class="col-md-3 col-sm-3">
				<div class="feature-center animate-box text-center" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-command"></i>
					</span>
					<h3>Aftersale Services</h3>
					<p>Treatment and care for customers as our responsibility and commitment. </p>
				</div>
			</div>
			<div class="col-md-3 col-sm-3">
				<div class="feature-center animate-box text-center" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-mouse"></i>
					</span>
					<h3>Affordable</h3>
					<p>With affordable price we can provide various type, patterns and kinds of carpets with the best quality.</p>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="fh5co-project">
	<div class="container">
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Our Products</h2>
				<div class="strip"></div>
				<!-- <p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p> -->
			</div>
		</div>
		<div class="row">
			<% @products.order(id: :desc).limit(3).each do |p| %>
          <div class="col-md-4 col-sm-6 fh5co-project animate-box" data-animate-effect="fadeIn">
            <%= link_to (p) do %>
              <%= image_tag(p.product_images.find_by(category:'thumbnail').name.url(:thumbnail)) %>
              <h3><%= p.name %></h3>
            <% end %> 
          </div>  
      <% end %>
		</div>
	</div>
</div>

<div id="fh5co-blog" class="fh5co-bg-section">
	<div class="container">
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Selected Portofolios</h2>
				<div class="strip"></div>
				<!-- <p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p> -->
			</div>
		</div>
		<div class="row">
			<% @portofolios.order(id: :desc).limit(3).each do |pp| %>
          <div class="col-md-4 col-sm-6 fh5co-project animate-box" data-animate-effect="fadeIn">
            <%= link_to (pp) do %>
              <%= image_tag(pp.portofolio_images.find_by(category:'thumbnail').name.url(:thumbnail)) %>
              <h3><%= pp.title %></h3>
            <% end %> 
          </div>  
      <% end %>
		</div>
	</div>
</div>


<div id="fh5co-testimonial"  style="background-image: url(<%= asset_path 'img_bg_33.jpg' %>); background-repeat:no-repeat; background-size: 100% 100%;">
	<div class="overlay"></div>
	<div class="container">
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Contact us now</h2>
				<div class="strip"></div>
				<p>For any questions concerning projects or inquiries, please just drop us an email.</p>
			</div>
		</div>
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2">
				<form class="form-inline">
					<div class="col-md-4 col-md-offset-4 col-sm-6 text-center">
						<%= link_to "Get in Touch", contact_path, class:'btn-scae-stroke-gold btn-block' %>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>